# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
    name: Azure Pipelines
    vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  displayName: Use Node
  inputs:
    version: 'Use Node 6.x'
    checkLatest: true
- task: Npm@1
  displayName: Install npm
  inputs:
    command: 'install'
    workingDir: 'WebApplication1/ClientApp'
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM Templetes'
  inputs:
    PathtoPublish: 'WebApp'
    ArtifactName: 'ARM'
    publishLocation: 'Container'
