# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build

pool:
    name: Azure Pipelines
    vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  displayName: Use Node
  inputs:
    version: 'Use Node 6.x'
    checkLatest: true
- task: Npm@1
  displayName: Install npm
  inputs:
    command: 'install'
    workingDir: 'WebApplication1/ClientApp'
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM Templetes'
  inputs:
    PathtoPublish: 'WebApp'
    ArtifactName: 'ARM'
    publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      name: 'windows-2019'
    variables:
      variables:
        ResourceGroupName: '$(Prefix)-$(Release.EnvironmentName)-$(Build.Buildid)-RG'
        LocationName: 'East US'
        WebAppName: '$(Prefix)-$(Release.EnvironmentName)-$(Build.Buildid)'

    steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure'
    subscriptionId: '1a35a0e9-7a1c-4123-8be0-c86e69bb0905'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroupName)'
    location: '$(LocationName)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ARM/WebSite.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/ARM/WebSite.parameters.json'
    overrideParameters: '-hostingPlanName "girishbh-service-plan-Test" -skuName "F1" -skuCapacity 1 -webSiteName $(WebAppName)'
    deploymentMode: 'Validation'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure'
    subscriptionId: '1a35a0e9-7a1c-4123-8be0-c86e69bb0905'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroupName)'
    location: '$(LocationName)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ARM/WebSite.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/ARM/WebSite.parameters.json'
    overrideParameters: '-hostingPlanName "girishbh-service-plan-Test" -skuName "F1" -skuCapacity 1 -webSiteName $(WebAppName)'
    deploymentMode: 'Incremental'